name: MinIO Upload and Remove

on:
  push:
    branches: [main]  # Change if your branch is named differently

jobs:
  minio-job:
    runs-on: ubuntu-latest

    container:
      image: minio/mc

    env:
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}

    steps:
    - name: Set up MinIO alias
      run: |
        mc alias set myminio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY

    - name: Create test file
      run: |
        echo "Hello from GitHub Actions!" > hello.txt

    - name: Upload file to MinIO
      run: |
        mc cp hello.txt myminio/my-bucket/hello.txt

    - name: Remove file from MinIO
      run: |
        mc rm myminio/my-bucket/hello.txt
