name: MinIO Standalone Test

on:
  push:
    branches: [main]

jobs:
  minio-test:
    runs-on: ubuntu-latest

    steps:
    - name: Install MinIO server
      run: |
        wget https://dl.min.io/server/minio/release/linux-amd64/minio
        chmod +x minio
        sudo mv minio /usr/local/bin/

    - name: Start MinIO server in background
      env:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
      run: |
        mkdir -p ~/minio-data
        nohup minio server ~/minio-data > minio.log 2>&1 &

    - name: Wait for MinIO to be ready
      run: |
        sleep 10
        curl -f http://localhost:9000/minio/health/live

    - name: Install MinIO client
      run: |
        curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/local/bin/

    - name: Setup MinIO alias
      run: mc alias set myminio http://localhost:9000 minioadmin minioadmin

    - name: Create bucket and upload a file
      run: |
        mc mb myminio/test
        echo "Hello from GitHub Actions!" > test.txt
        mc cp test.txt myminio/test/

    - name: List files
      run: mc ls myminio/test/

    - name: Download and show contents of uploaded file
      run: |
        mc cp myminio/test/test.txt downloaded.txt
        echo "File contents:"
        cat downloaded.txt


    - name: Delete file
      run: mc rm myminio/test/test.txt
