name: MinIO Remote Test

on:
  push:
    branches: [main]

jobs:
  minio-test:
    runs-on: ubuntu-latest

    steps:
    - name: Install MinIO client
      run: |
        curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/local/bin/

    - name: Setup MinIO alias (with remote URL)
      run: |
        mc alias set myminio http://localhost:9001 minioadmin minioadmin

    - name: Make a bucket and upload a file
      run: |
        mc mb myminio/mybucket
        echo "Hello from GitHub Actions!" > test.txt
        mc cp test.txt myminio/mybucket/

    - name: List files in bucket
      run: mc ls myminio/test/

    - name: Remove file from bucket
      run: mc rm myminio/test/test.txt
