name: MinIO Upload and Remove

on:
  push:
    branches: [main]

jobs:
  minio-job:
    runs-on: ubuntu-latest

    # This tells GitHub to run your job inside this Docker container
    container:
      image: minio/mc

    env:
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}

    steps:
    - name: Setup MinIO alias
      run: |
        mc alias set myminio http://localhost:9001 my-access-key my-secret-key

    - name: Create a test file
      run: |
        echo "Hello from GitHub Actions!" > hello.txt

    - name: Upload to MinIO
      run: |
        mc cp hello.txt myminio/test/hello.txt

    - name: Remove from MinIO
      run: |
        mc rm myminio/test/hello.txt
